language:
  - c

before_install:
  - pip install --user cpp-coveralls
  
addons:
  sonarcloud:
    organization: "evolkova01"
    token:
      secure: "E7llIWAChgNKx8XbIH16SUIdlbLdZxTAi7KfRSwqoI866K1NR8UHJZVPunb3CIOJeTKX+QanhOK8c0haOrTw5vKt08QKe2Lr5Uu8ybxpTOWcG5fZQoEX9NjuSW2tnvN12EDK3YnQcVIHzvAZko33hc/rUQYTV8WInq0jBH1VK6i3D+9oCJkNtuQ/oLhB2PsErKpO0DMU2pUkE0ehBY22o1MZvPgS3heQiNnPHiwOKDwL1XqBkvUX6Gx9cvebNwJA7RcKmzuA/DG6+u0s1XmpTqGseMb3gOG/UVYTj69+Cj7BIipQQPmCm6fb1s3JyofdUI6uthiwa4xzRYw7Y5xjcCh49h/5xsePwEuZEvWWU4SnW2fzoCgKTELJY306ux28T5JaTpmBylEWCSsFNDCiDL3dFZ2BVslxWUSnXnVrZIM0D98ExOESrzeSdkWbygVdc2ZXx5R8ZbIgjYiBek6Typ1/9emZHCeLGM7hmWVPl5Ox8pdPC/rB3hS/FCRrnBtKs23p1Qwzn/39X5/Gr8sy4OeDJT+zEA3ePKumXiQLILGIt9V+Uah9bV6uXFgkY7xkFxMc6DbKhbzuckaCHao6Vpm5pyd/0h6oNUALD2JLdr4HtFs11OxEzqONK4U2SN0ca9HGIvzU7rKj0m37Sq21vCBE/mp7BVNRWH9FYnFjfr4="

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
  
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'  

notifications:
  email: false
